alias agaa="\"${PROGRAMEIRO_RUNNER}\" m/sources/git/auto_commit_all"
alias agan="\"${PROGRAMEIRO_RUNNER}\" m/sources/git/auto_commit_new"
alias asrc="\"${PROGRAMEIRO_RUNNER}\" s/eac-tools source"
alias aur='docker compose run app /aux/app_user_run.sh'
alias bcop="ehb m/sources/ruby/rubocop/source_run"
alias bcops="bcop -a"
alias bcopu="bcop -A"
alias bspc="bundle exec rspec --fail-fast --format doc"
alias bii="bundle --local && bundle --local"
alias bui="ehb s/eac-tools source bundle update && ehb s/eac-tools source bundle install"
alias cagaa="USE_CLIUTILS=t agaa"
alias cagan="USE_CLIUTILS=t agan"
alias casrc="USE_CLIUTILS=t asrc"
alias cdretro='cd ~/opt/games/retroarch/RetroArch-Linux-x86_64.AppImage.home/.config/retroarch'
alias cdgems='cd ~/.asdf/installs/ruby/*/lib/ruby/gems/*/gems'
alias ccd="${PROGRAMEIRO_RUNNER} m/code/clean_dirty"
alias ccdc="${PROGRAMEIRO_RUNNER} m/code/clean_dirty && git add . && git rc"
alias csrc="\"${PROGRAMEIRO_RUNNER}\" s/avm-cliutils source"
alias cln="${PROGRAMEIRO_RUNNER} m/code/clean"
alias dst="docker compose -f docker-stack.yml"
alias fbn="${PROGRAMEIRO_RUNNER} f/find/by-name"
alias fbnm="${PROGRAMEIRO_RUNNER} f/find/by-name-move"
alias ga.="git add ."
alias gact="git add . && git commit"
alias gra="git avm-rebase"
alias grb="git rebase --abort"
alias gri="git rebase --interactive"
alias gst="git status"
alias gcg="git commit --message"
alias gct="git ct"
alias vprobe="'${PROGRAMEIRO_RUNNER}' s/ehbrs-tools videos probe"
alias vbum="${PROGRAMEIRO_RUNNER} m/sources/version_bump/minor"
alias vbup="${PROGRAMEIRO_RUNNER} m/sources/version_bump/patch"
alias weac="\"${PROGRAMEIRO_RUNNER}\" s/eac-tools"
alias wehbrs="\"${PROGRAMEIRO_RUNNER}\" s/ehbrs-tools"
