alias agaa="\"${MYSELF_RUN}\" m/sources/git/auto_commit_all"
alias agan="\"${MYSELF_RUN}\" m/sources/git/auto_commit_new"
alias asrc="\"${MYSELF_RUN}\" w/avm source"
alias aur='docker compose run app /aux/app_user_run.sh'
alias b150i="\"${MYSELF_RUN}\" e/ehbrs/bbfln/150/cliutils e/ehbrs/bbfln/150/install/all"
alias b200i="\"${MYSELF_RUN}\" e/ehbrs/bbfln/200/cliutils e/ehbrs/bbfln/200/install/all"
alias bcop="ehb m/sources/ruby/rubocop/source_run"
alias bcops="bcop -a"
alias bcopu="bcop -A"
alias bspc="bundle exec rspec --fail-fast --format doc"
alias bui="ehb w/avm source bundle update && ehb w/avm source bundle install"
alias cagaa="USE_CLIUTILS=t agaa"
alias cagan="USE_CLIUTILS=t agan"
alias casrc="USE_CLIUTILS=t asrc"
alias cdretro='cd ~/opt/games/retroarch/RetroArch-Linux-x86_64.AppImage.home/.config/retroarch'
alias cdgems='cd ~/.asdf/installs/ruby/*/lib/ruby/gems/*/gems'
alias ccd="${MYSELF_RUN} m/code/clean_dirty"
alias ccdc="${MYSELF_RUN} m/code/clean_dirty && git add . && git rc"
alias csrc="\"${MYSELF_RUN}\" w/avm-cliutils source"
alias cln="${MYSELF_RUN} m/code/clean"
alias dst="docker compose -f docker-stack.yml"
alias fbn="${MYSELF_RUN} f/find/by-name"
alias gra="git avm-rebase"
alias grb="git rebase --abort"
alias gri="git rebase --interactive"
alias gst="git status"
alias gcg="git commit --message"
alias vprobe="'${MYSELF_RUN}' w/ehbrs videos probe"
alias vbum="${MYSELF_RUN} m/sources/version_bump/minor"
alias vbup="${MYSELF_RUN} m/sources/version_bump/patch"
alias wavm="\"${MYSELF_RUN}\" w/avm"
alias weac="\"${MYSELF_RUN}\" s/eac-tools"
alias wehbrs="\"${MYSELF_RUN}\" w/ehbrs"
alias wpd1="\"${MYSELF_RUN}\" /s/pd1-tools"
